### ISSUE TITLE
Mise à jour des épisodes 

### ISSUE THREAD

**Issue by mo418** [anisite/plugin.video.vtele#2]
Bonjour,

Pour que la liste des épisodes (un souper presque parfait, dans mon cas) se mettent à jour et que je puisse voir celui de la journée, je dois réinstaller manuellement l'Addon à chaque fois. 

Serait-ce possible d'ajouter une fonction qui permettrait une mise à jour auto des épisodes sans avoir à réinstaller l'addon (par zip).

Merci d'avance

**Comment by anisite** [comment]
Bonjour, sur quel os est tu et est-ce que l'heure de ton système et la date sont bonnes?

**Comment by mo418** [comment]
Salut,

Je suis sur Windows 10 et la date et l’heure du mon système sont bonnes.

J’utilise Kodi Leia (64 bits)

**Comment by mo418** [comment]
Salut,

Aviez-vous eu le temps de regarder ça un peu? Le problème persiste. 

Merci encore

**Comment by anisite** [comment]
@mo418 je n'arrive pas a reproduire le problème, cela arrive t-il avec toutes les émissions ou seulement quelques unes, il est possible que si l'émission sort a 18h pile et que l'ont consulte les épisodes juste avant que cela prenne un bon bout de temps avant que la nouvelle apparaisse a cause du cache. Mais si ça fait 24h que vous m'avez pas consulter les épisodes et qu'en rentrant ils ne soient pas là... j'explique mal.

**Comment by mo418** [comment]
Je n’ai pas regardé pour les autres émissions. 

Je consulte les épisodes au moins 24h après leur sorties. Parfois c’est après quelques jours. Je dois toujours mettre à jour l’addon sinon il n’y a rien de nouveau.

Je vais tenter de voir avec d’autres émissions et je te reviens.

Merci pour le retour rapide!

**Comment by anisite** [comment]
J'ai retiré le caching dans la dernière version. Le problème est-il toujours là?

**Comment by mo418** [comment]
Bonsoir,
Tout semblait fonctionner jusqu'à hier. Et j'ai vérifié il y a quelques minutes et les épisodes arrêtent à jeudi. Celui de ce soir n'est pas dispo. Merci :)

**Comment by anisite** [comment]
Étrange, je viens de regarder même chose ici. Le site est ok, mais c'est certain que j'ai pas de caching. Peut être que c'est un paramètre qui est différent entre moi et eux

**Comment by mo418** [comment]
À environ 22h, toutes les épisodes sont là. Est-ce que ça serait un problème de communication (temps de refresh)? Je ne connais pas vraiment ça, je lance ça comme ça :)
