### ISSUE TITLE
la tuile films ne fonctionne pas

### ISSUE THREAD

**Issue by maquintal** [anisite/plugin.video.vtele#3]
lorsque je tente d'ouvrir la tuile ca m'affiche error 

6   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vtele/?filters=%7b%22content%22%3a%20%7b%22url%22%3a%20%22https%3a%2f%2fnoovo.ca%2ffilms%22%2c%20%22genreId%22%3a%201%2c%20%22afficherTous%22%3a%20false%2c%20%22mediaBundleId%22%3a%20-1%7d%2c%20%22sourceId%22%3a%20%22%22%2c%20%22fullNameItems%22%3a%20%5b%5d%2c%20%22show%22%3a%20%7b%22Episode%22%3a%20%22%22%2c%20%22Saison%22%3a%20%22%22%2c%20%22label%22%3a%20%22%22%7d%7d&mode=1&url=https%3a%2f%2fnoovo.ca%2ffilms) failed

**Comment by anisite** [comment]
Bonjour effectivement cette section est différente et elle n'est pas supportée. Je vais voir ce que je peux faire... Je ne peux pas donner de date malheureusement.
