### ISSUE TITLE
Ne fonctionne plus suite à une modification du site

### ISSUE THREAD

**Issue by gabtremblay** [anisite/plugin.video.vtele#4]
Il y a eu une mise a jour mineure sur noovo.ca. Le repertoire des "shows" fonctionne encore, mais tous les épisodes sont maintenant "vides" dans le plugin.

**Comment by anisite** [comment]
La version 0.6.2 corrige le problème, merci!

**Comment by gabtremblay** [comment]
Ça fonctionne a merveille, merci!
