### ISSUE TITLE
Mise à jour liens

### ISSUE THREAD

**Issue by kevint277** [anisite/plugin.video.vtele#5]
Bonjour!

Avec le changement de nom de la chaîne, je crois que certains liens ne fonctionnent plus. C'est le cas pour Occupation Double, par exemple. On voit OD dans le choix d'émissions, mais lorsqu'on tombe dans le menu, on ne peut que jouer des vidéos de pub, et non les épisodes. Merci 👍

**Comment by anisite** [comment]
OD ça toujours été un monde à part. C'est ou cette année la ? Je vois Afrique du sud... y'a comme une sous-émission "CHEZ NOUS" c'est weird... bref va falloir je creuse un peu, j'écoute pas cette émission la, pas trop au courant.

**Comment by kevint277** [comment]
Ouais, toujours bizarre en effet.. C'est OD chez nous, les épisodes sont
tous ici: https://noovo.ca/emissions/occupation-double/chez-nous/episodes

**Comment by anisite** [comment]
Bonjour, une correction est présentement en déploiement (version 1.0.1) vous pouvez la forcer pour voir si ça corrige le problème. ça semble faire le travail de mon bord. merci de me revenir!

**Comment by kevint277** [comment]
Ça fonctionne numéro 1. Merci beaucoup pour ton travail!
